import { StyleSheet } from 'react-native';

export const controlStyles = StyleSheet.create({
  knobsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  knobCol: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    minWidth: 108,
  },
  powerCol: {
    width: 58,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 2,
    gap: 4,
  },
  waveReadout: {
    width: '100%',
    paddingVertical: 3,
    paddingHorizontal: 2,
    borderRadius: 6,
    borderWidth: 2,
    borderTopColor: '#7a5c40',
    borderLeftColor: '#5c4430',
    borderRightColor: '#1c1410',
    borderBottomColor: '#0c0806',
    backgroundColor: '#0f0c0a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.45,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  waveReadoutDim: {
    opacity: 0.42,
  },
  waveReadoutValue: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 14,
    color: '#e8c896',
    letterSpacing: 0.4,
    textShadowColor: 'rgba(255, 140, 60, 0.35)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  waveReadoutUnit: {
    marginTop: -2,
    fontFamily: 'Oswald_400Regular',
    fontSize: 8,
    letterSpacing: 1.2,
    color: 'rgba(184, 155, 120, 0.85)',
    textTransform: 'lowercase',
  },
  powerPressable: {
    alignItems: 'center',
  },
  powerPressablePressed: {
    opacity: 0.88,
    transform: [{ translateY: 1 }],
  },
  powerHousing: {
    width: 54,
    height: 30,
    borderRadius: 7,
    borderWidth: 2,
    borderTopColor: '#7a5c40',
    borderLeftColor: '#5c4430',
    borderRightColor: '#1c1410',
    borderBottomColor: '#0c0806',
    overflow: 'hidden',
    justifyContent: 'center',
    backgroundColor: '#16110e',
    shadowColor: '#000',
    shadowOpacity: 0.55,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  powerHousingGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 5,
  },
  powerBevel: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 5,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,220,180,0.06)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.35)',
  },
  powerTrack: {
    alignSelf: 'center',
    width: 42,
    height: 12,
    borderRadius: 3,
    backgroundColor: '#050403',
    borderWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.85)',
    borderLeftColor: 'rgba(0,0,0,0.5)',
    borderRightColor: 'rgba(255,200,140,0.06)',
    borderBottomColor: 'rgba(255,220,200,0.04)',
    position: 'relative',
    justifyContent: 'center',
  },
  powerThumb: {
    position: 'absolute',
    top: 2,
    width: 18,
    height: 8,
    borderRadius: 2,
    borderWidth: 1,
    borderTopColor: 'rgba(255,240,210,0.35)',
    borderLeftColor: 'rgba(255,240,210,0.12)',
    borderRightColor: 'rgba(0,0,0,0.45)',
    borderBottomColor: 'rgba(0,0,0,0.55)',
    overflow: 'hidden',
  },
  powerThumbOff: {
    left: 2,
  },
  powerThumbOn: {
    left: 22,
  },
  powerStateLabel: {
    marginTop: 3,
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 9,
    letterSpacing: 1.4,
  },
  powerStateLabelOn: {
    color: '#c9f0c4',
    textShadowColor: 'rgba(80, 200, 90, 0.35)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  powerStateLabelOff: {
    color: '#6a5a4a',
  },
  powerCaption: {
    marginTop: 1,
    fontFamily: 'Oswald_400Regular',
    fontSize: 8,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: 'rgba(184,155,120,0.65)',
  },
  knobOuter: {
    borderRadius: 999,
    borderWidth: 3,
    borderTopColor: '#a9835a',
    borderLeftColor: '#8b6b48',
    borderRightColor: '#332417',
    borderBottomColor: '#1d130c',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#16110e',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  knobOuterDisabled: {
    opacity: 0.38,
  },
  knobGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  knobRim: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: 8,
    bottom: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,220,180,0.18)',
  },
  knobInnerRing: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 14,
    bottom: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  knobCore: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 16,
    bottom: 16,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  knobIndicatorWrap: {
    position: 'absolute',
    top: 8,
    bottom: 8,
    left: 8,
    right: 8,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  knobIndicator: {
    width: 3,
    height: 28,
    borderRadius: 999,
    shadowColor: '#ffb45a',
    shadowOpacity: 0.75,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  knobLabel: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  knobLabelDim: {
    opacity: 0.35,
  },
});
