import { StyleSheet } from 'react-native';

export const panelStyles = StyleSheet.create({
  panel: {
    borderRadius: 12,
    padding: 4,
    borderWidth: 2,
    borderTopColor: '#a98154',
    borderLeftColor: '#765737',
    borderRightColor: '#2f2015',
    borderBottomColor: '#1b120c',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.58,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  panelBevel: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,229,185,0.08)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.44)',
  },
  row: {
    flexDirection: 'row',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  blockBtn: {
    flex: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,230,185,0.035)',
  },
  blockText: {
    color: '#b89b78',
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  blockTextActive: {
    color: '#ffd9a0',
  },
  blockActiveUssr: {
    backgroundColor: '#3b0b08',
    borderTopColor: '#8f2a23',
    borderLeftColor: '#6d1916',
    borderRightColor: '#250604',
    borderBottomColor: '#160302',
  },
  blockActiveAxis: {
    backgroundColor: '#1f1f1f',
    borderTopColor: '#626262',
    borderLeftColor: '#474747',
    borderRightColor: '#141414',
    borderBottomColor: '#090909',
  },
  blockActiveAllies: {
    backgroundColor: '#0d2238',
    borderTopColor: '#245883',
    borderLeftColor: '#183d66',
    borderRightColor: '#071521',
    borderBottomColor: '#040b11',
  },
  controlPressed: {
    transform: [{ translateY: 1 }, { scale: 0.985 }],
    shadowOpacity: 0.1,
    opacity: 0.88,
  },
  controlDisabled: {
    shadowColor: '#ffba62',
    shadowOpacity: 0.45,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 7,
  },
  yearBtn: {
    flex: 1,
    minWidth: 0,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  yearIdle: {
    backgroundColor: '#1e1712',
    borderTopColor: 'rgba(255,224,180,0.08)',
    borderLeftColor: 'rgba(255,224,180,0.05)',
    borderRightColor: 'rgba(0,0,0,0.3)',
    borderBottomColor: 'rgba(0,0,0,0.48)',
  },
  yearActive: {
    backgroundColor: '#c79852',
    borderTopColor: '#f1c77d',
    borderLeftColor: '#d9a65e',
    borderRightColor: '#7f5528',
    borderBottomColor: '#52320f',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  yearText: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 13,
    color: '#b89b78',
    letterSpacing: 0.5,
  },
  yearTextActive: {
    color: '#1d140e',
  },
});
