import { StyleSheet } from 'react-native';

export const playlistStyles = StyleSheet.create({
  promoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 210, 150, 0.14)',
    backgroundColor: 'rgba(28, 20, 14, 0.92)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 10,
    overflow: 'hidden',
  },
  promoCrate: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: 'rgba(90, 55, 35, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255, 200, 130, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoCrateLabel: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 7,
    letterSpacing: 0.5,
    color: 'rgba(255, 220, 170, 0.75)',
    textAlign: 'center',
    marginTop: 2,
  },
  promoBody: {
    flex: 1,
    minWidth: 0,
  },
  promoTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 13,
    letterSpacing: 1.2,
    color: '#f5d2a2',
  },
  promoSubtitle: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 10,
    color: '#9d7b58',
    marginTop: 2,
    lineHeight: 14,
  },
  promoModeBadge: {
    marginTop: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: 'rgba(142, 21, 13, 0.55)',
  },
  promoModeBadgeText: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 9,
    letterSpacing: 1,
    color: '#ffd7a4',
  },
  promoArrow: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 18,
    color: '#c9a06a',
    paddingHorizontal: 4,
  },
  screenRoot: {
    flex: 1,
    backgroundColor: '#15120f',
  },
  screenInner: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  playlistHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerBackBtn: {
    minWidth: 72,
    paddingVertical: 6,
    paddingRight: 12,
  },
  headerSpacer: {
    minWidth: 72,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  backBtn: {
    paddingVertical: 6,
    paddingRight: 12,
  },
  backBtnText: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    color: '#c9a06a',
    letterSpacing: 1,
  },
  playlistTitle: {
    flex: 1,
    fontFamily: 'PlayfairDisplay_700Bold_Italic',
    textAlign: 'center',
    color: '#f7ddb6',
  },
  playerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 196, 120, 0.12)',
    backgroundColor: 'rgba(18, 13, 9, 0.95)',
    padding: 14,
    marginBottom: 14,
  },
  playerBarText: {
    flex: 1,
    minWidth: 0,
  },
  playerLabel: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 11,
    letterSpacing: 2,
    color: '#8e7152',
    marginBottom: 4,
  },
  playerTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 22,
    color: '#f8ddb1',
  },
  playerMeta: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    color: '#b99267',
    marginTop: 4,
  },
  modeSwitchRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  modeBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#1a120d',
    borderWidth: 1,
    borderColor: 'rgba(255, 210, 150, 0.08)',
  },
  modeBtnActive: {
    backgroundColor: '#5a0906',
    borderColor: 'rgba(255, 160, 120, 0.25)',
  },
  modeBtnText: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 13,
    letterSpacing: 1.5,
    color: '#9d7b58',
  },
  modeBtnTextActive: {
    color: '#ffd7a4',
  },
  searchInput: {
    backgroundColor: '#120d09',
    borderWidth: 1,
    borderColor: 'rgba(255, 211, 149, 0.1)',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#f7ddb6',
    fontFamily: 'Oswald_400Regular',
    fontSize: 15,
    marginBottom: 12,
  },
  sectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 22,
    color: '#f5d2a2',
  },
  sectionCount: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 12,
    letterSpacing: 1.5,
    color: '#b28a63',
  },
  trackList: {
    flex: 1,
    gap: 12,
  },
  trackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 153, 0.08)',
    backgroundColor: 'rgba(24, 18, 12, 0.98)',
    padding: 14,
  },
  trackCover: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: 'rgba(90, 45, 32, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackInfo: {
    flex: 1,
    minWidth: 0,
  },
  trackTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 18,
    color: '#f7ddb6',
    marginBottom: 6,
  },
  trackMeta: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 13,
    color: '#a8845f',
  },
  trackActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trackActionBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#1b120d',
    borderWidth: 1,
    borderColor: 'rgba(255, 210, 150, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackEditText: {
    fontSize: 18,
    color: '#f5cf9b',
    lineHeight: 20,
  },
  trackDeleteText: {
    fontSize: 20,
    color: '#f5cf9b',
    lineHeight: 22,
  },
  addCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 153, 0.12)',
    backgroundColor: 'rgba(24, 18, 12, 0.95)',
    paddingVertical: 18,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  addVinylWrap: {
    marginBottom: 12,
  },
  addTitle: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 20,
    color: '#f7ddb6',
    marginBottom: 6,
  },
  addHint: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    color: '#b38b64',
    textAlign: 'center',
    lineHeight: 20,
  },
  busyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  busyText: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    color: '#b99267',
  },
  emptyHint: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    color: '#8e7152',
    textAlign: 'center',
    paddingVertical: 24,
    lineHeight: 20,
  },
  festivalBanner: {
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    backgroundColor: 'rgba(255, 190, 110, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 210, 150, 0.12)',
  },
  festivalBannerText: {
    fontFamily: 'Oswald_400Regular',
    fontSize: 13,
    color: '#b99267',
    lineHeight: 18,
    textAlign: 'center',
  },
  vinyl: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#151515',
    borderWidth: 2,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vinylLabel: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#a84332',
  },
});
