import { StyleSheet } from 'react-native';

export const radioBodyStyles = StyleSheet.create({
  radioBody: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 2,
    borderTopColor: '#a37d52',
    borderLeftColor: '#8d6b47',
    borderRightColor: '#3f2d20',
    borderBottomColor: '#241811',
    backgroundColor: '#241b15',
    shadowColor: '#000',
    shadowOpacity: 0.86,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 14,
  },
  innerPad: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 6,
  },
  bodyFill: {
    ...StyleSheet.absoluteFillObject,
  },
  bodyRadialLike: {
    position: 'absolute',
    left: '-15%',
    top: '-18%',
    width: '130%',
    height: '45%',
    borderRadius: 999,
    opacity: 0.9,
  },
  bodyNoise: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  bodyInsetShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderWidth: 8,
    borderTopColor: 'rgba(255,224,176,0.08)',
    borderLeftColor: 'rgba(255,224,176,0.035)',
    borderRightColor: 'rgba(0,0,0,0.24)',
    borderBottomColor: 'rgba(0,0,0,0.36)',
  },
  bodyTopBevel: {
    position: 'absolute',
    top: 0,
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: 'rgba(255,226,174,0.22)',
  },
  bodyBottomVignette: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '22%',
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  titleWrap: {
    alignItems: 'center',
  },
  title: {
    color: '#f4e6cf',
    fontFamily: 'PlayfairDisplay_700Bold_Italic',
    letterSpacing: 0.4,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  titleLightsOff: {
    opacity: 0.32,
    textShadowRadius: 2,
  },
});
