import { StyleSheet } from 'react-native';

export const scaleStyles = StyleSheet.create({
  scale: {
    flex: 1,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 6,
    borderWidth: 2,
    borderTopColor: '#b88955',
    borderLeftColor: '#8d6b47',
    borderRightColor: '#3b281a',
    borderBottomColor: '#21150d',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  scaleInnerShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 14,
    borderWidth: 6,
    borderTopColor: 'rgba(0,0,0,0.42)',
    borderLeftColor: 'rgba(0,0,0,0.22)',
    borderRightColor: 'rgba(255,210,145,0.025)',
    borderBottomColor: 'rgba(255,180,90,0.06)',
  },
  scaleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  scaleBand: {
    color: '#d5b78d',
    fontFamily: 'Oswald_400Regular',
    fontSize: 9,
    letterSpacing: 1.4,
  },
  scaleTicksWrap: {
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
  },
  ticksRow: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  tick: {
    borderRadius: 999,
  },
  tickMajor: {
    height: '52%',
    width: 2,
    backgroundColor: '#e6d1b2',
    opacity: 0.9,
  },
  tickMinor: {
    height: '22%',
    width: 1,
    backgroundColor: '#b89b78',
    opacity: 0.85,
  },
  slider: {
    position: 'absolute',
    left: 0,
    top: '6%',
    bottom: '22%',
    width: 3,
    borderRadius: 999,
    backgroundColor: '#ff9830',
    shadowColor: '#ff7a14',
    shadowOpacity: 0.9,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
    marginLeft: -1.5,
  },
  scaleBottomRow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '20%',
    minHeight: 14,
  },
  scaleMarkAnchor: {
    position: 'absolute',
    width: 36,
    marginLeft: -18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scaleNumber: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_400Regular',
    fontSize: 9,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  scaleTextDim: {
    opacity: 0.35,
  },
  scaleGlassSheen: {
    position: 'absolute',
    left: -40,
    top: -24,
    width: '75%',
    height: '70%',
    opacity: 0.95,
    transform: [{ rotate: '-13deg' }],
  },
  scaleGlassMist: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,244,220,0.035)',
  },
});
