import { StyleSheet } from 'react-native';
import { CARD_W } from '../theme/layout';

export const scaleStyles = StyleSheet.create({
  scale: {
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderTopColor: '#b88955',
    borderLeftColor: '#8d6b47',
    borderRightColor: '#3b281a',
    borderBottomColor: '#21150d',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  scaleInnerShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.42)',
    borderLeftColor: 'rgba(0,0,0,0.22)',
    borderRightColor: 'rgba(255,210,145,0.025)',
    borderBottomColor: 'rgba(255,180,90,0.06)',
  },
  scaleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  scaleBand: {
    color: '#d5b78d',
    fontFamily: 'Oswald_400Regular',
    fontSize: 11,
    letterSpacing: 1.8,
  },
  scaleTicksWrap: {
    height: 84,
    justifyContent: 'center',
  },
  ticksRow: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  tick: {
    borderRadius: 999,
  },
  tickMajor: {
    height: 42,
    width: 2,
    backgroundColor: '#e6d1b2',
    opacity: 0.9,
  },
  tickMinor: {
    height: 18,
    width: 1,
    backgroundColor: '#b89b78',
    opacity: 0.85,
  },
  slider: {
    position: 'absolute',
    left: 0,
    top: 6,
    bottom: 24,
    width: 3,
    borderRadius: 999,
    backgroundColor: '#ff9830',
    shadowColor: '#ff7a14',
    shadowOpacity: 0.9,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
    marginLeft: -1.5,
  },
  scaleBottomRow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 22,
  },
  scaleMarkAnchor: {
    position: 'absolute',
    width: 44,
    marginLeft: -22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scaleNumber: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_400Regular',
    fontSize: 11,
    letterSpacing: 0.7,
    textAlign: 'center',
  },
  scaleTextDim: {
    opacity: 0.35,
  },
  scaleGlassSheen: {
    position: 'absolute',
    left: -40,
    top: -28,
    width: CARD_W * 0.72,
    height: 90,
    opacity: 0.95,
    transform: [{ rotate: '-13deg' }],
  },
  scaleGlassMist: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,244,220,0.035)',
  },
});
