import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bg: {
    flex: 1,
    backgroundColor: '#1a0f08',
  },
  woodBase: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#3d2817',
  },
  woodPanelLeft: {
    position: 'absolute',
    left: 0,
    top: '6%',
    bottom: '6%',
    width: '14%',
    backgroundColor: '#352010',
    borderRightWidth: 2,
    borderRightColor: 'rgba(180, 140, 70, 0.35)',
  },
  woodPanelRight: {
    position: 'absolute',
    right: 0,
    top: '6%',
    bottom: '6%',
    width: '14%',
    backgroundColor: '#352010',
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(180, 140, 70, 0.35)',
  },
  brassTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 10,
    backgroundColor: 'rgba(201, 162, 82, 0.45)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(90, 70, 40, 0.6)',
  },
  brassBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 10,
    backgroundColor: 'rgba(201, 162, 82, 0.4)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(90, 70, 40, 0.55)',
  },
  brassCornerTL: {
    position: 'absolute',
    left: 10,
    top: 14,
    width: 28,
    height: 28,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderColor: 'rgba(212, 175, 95, 0.55)',
    borderRadius: 2,
  },
  brassCornerTR: {
    position: 'absolute',
    right: 10,
    top: 14,
    width: 28,
    height: 28,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderColor: 'rgba(212, 175, 95, 0.55)',
    borderRadius: 2,
  },
  grille: {
    ...StyleSheet.absoluteFillObject,
    marginHorizontal: '8%',
    marginVertical: '18%',
    borderWidth: 2,
    borderColor: 'rgba(90, 70, 45, 0.45)',
    borderRadius: 6,
    backgroundColor: 'rgba(0,0,0,0.12)',
  },
  content: {
    flex: 1,
    zIndex: 2,
  },
  warmupOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: '#0a0604',
  },
});
