import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const CARD_W = Math.min(SCREEN_W - 32, 390);

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#15120f',
  },
  scroll: {
    minHeight: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  radioBody: {
    width: CARD_W,
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#7f6243',
    backgroundColor: '#241b15',
    shadowColor: '#000',
    shadowOpacity: 0.75,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  innerPad: {
    padding: 18,
  },
  bodyFill: {
    ...StyleSheet.absoluteFillObject,
  },
  bodyRadialLike: {
    position: 'absolute',
    left: -CARD_W * 0.2,
    top: -CARD_W * 0.25,
    width: CARD_W * 1.2,
    height: CARD_W * 0.9,
    borderRadius: 999,
    opacity: 0.9,
  },
  bodyNoise: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  titleWrap: {
    alignItems: 'center',
    marginBottom: 18,
  },
  title: {
    color: '#d8c3a5',
    fontSize: 24,
    letterSpacing: 3.2,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 6,
    color: '#b89b78',
    fontSize: 14,
    letterSpacing: 4.0,
    textTransform: 'uppercase',
  },
  scale: {
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#8d6b47',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.55,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  scaleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  scaleBand: {
    color: '#d5b78d',
    fontSize: 11,
    letterSpacing: 1.4,
  },
  scaleTicksWrap: {
    height: 84,
    justifyContent: 'center',
  },
  ticksRow: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  tick: {
    borderRadius: 999,
  },
  tickMajor: {
    height: 42,
    width: 2,
    backgroundColor: '#e6d1b2',
    opacity: 0.9,
  },
  tickMinor: {
    height: 18,
    width: 1,
    backgroundColor: '#b89b78',
    opacity: 0.85,
  },
  slider: {
    position: 'absolute',
    top: 6,
    bottom: 24,
    width: 3,
    borderRadius: 999,
    backgroundColor: '#ff9830',
    shadowColor: '#ff7a14',
    shadowOpacity: 0.9,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
    marginLeft: -1.5,
  },
  scaleBottomRow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scaleNumber: {
    color: '#d8c3a5',
    fontSize: 11,
  },
  panel: {
    borderRadius: 18,
    padding: 8,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#856543',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  row: {
    flexDirection: 'row',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  blockBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blockText: {
    color: '#b89b78',
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  blockTextActive: {
    color: '#ffd9a0',
  },
  blockActiveUssr: {
    backgroundColor: '#3b0b08',
  },
  blockActiveAxis: {
    backgroundColor: '#1f1f1f',
  },
  blockActiveAllies: {
    backgroundColor: '#0d2238',
  },
  yearBtn: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearIdle: {
    backgroundColor: '#1e1712',
  },
  yearActive: {
    backgroundColor: '#c79852',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  yearText: {
    fontSize: 16,
    color: '#b89b78',
    fontWeight: '700',
  },
  yearTextActive: {
    color: '#1d140e',
  },
  stationsWrap: {
    gap: 10,
    marginBottom: 18,
  },
  stationCard: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(141,107,71,0.35)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  stationLeft: {
    flexDirection: 'column',
    gap: 2,
  },
  stationCity: {
    color: '#f2dfc2',
    fontSize: 16,
    fontWeight: '700',
  },
  stationBlock: {
    color: '#8e775b',
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  stationFreq: {
    color: '#d8c3a5',
    fontSize: 14,
    fontWeight: '600',
  },
  knobsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  knobCol: {
    alignItems: 'center',
    gap: 10,
  },
  knobOuter: {
    width: 112,
    height: 112,
    borderRadius: 999,
    borderWidth: 4,
    borderColor: '#8b6b48',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#16110e',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  knobGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  knobRim: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    bottom: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,220,180,0.18)',
  },
  knobInnerRing: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 18,
    bottom: 18,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  knobCore: {
    position: 'absolute',
    left: 22,
    right: 22,
    top: 22,
    bottom: 22,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  knobIndicatorWrap: {
    position: 'absolute',
    top: 12,
    bottom: 12,
    left: 12,
    right: 12,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  knobIndicator: {
    width: 4,
    height: 40,
    borderRadius: 999,
    shadowColor: '#ffb45a',
    shadowOpacity: 0.75,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  knobLabel: {
    color: '#d8c3a5',
    fontSize: 11,
    letterSpacing: 2.8,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
});

