import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const CARD_W = Math.min(SCREEN_W - 32, 390);

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#15120f',
  },
  scroll: {
    minHeight: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  radioBody: {
    width: CARD_W,
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 2,
    borderTopColor: '#a37d52',
    borderLeftColor: '#8d6b47',
    borderRightColor: '#3f2d20',
    borderBottomColor: '#241811',
    backgroundColor: '#241b15',
    shadowColor: '#000',
    shadowOpacity: 0.86,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 18 },
    elevation: 14,
  },
  innerPad: {
    padding: 18,
  },
  bodyFill: {
    ...StyleSheet.absoluteFillObject,
  },
  bodyRadialLike: {
    position: 'absolute',
    left: -CARD_W * 0.2,
    top: -CARD_W * 0.25,
    width: CARD_W * 1.2,
    height: CARD_W * 0.9,
    borderRadius: 999,
    opacity: 0.9,
  },
  bodyNoise: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)',
  },
  bodyInsetShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
    borderWidth: 10,
    borderTopColor: 'rgba(255,224,176,0.08)',
    borderLeftColor: 'rgba(255,224,176,0.035)',
    borderRightColor: 'rgba(0,0,0,0.24)',
    borderBottomColor: 'rgba(0,0,0,0.36)',
  },
  bodyTopBevel: {
    position: 'absolute',
    top: 0,
    left: 16,
    right: 16,
    height: 2,
    backgroundColor: 'rgba(255,226,174,0.22)',
  },
  bodyBottomVignette: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 135,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  titleWrap: {
    alignItems: 'center',
    marginBottom: 18,
  },
  title: {
    color: '#f4e6cf',
    fontFamily: 'PlayfairDisplay_700Bold_Italic',
    fontSize: 40,
    letterSpacing: 0.5,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
  },
  scale: {
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderTopColor: '#b88955',
    borderLeftColor: '#8d6b47',
    borderRightColor: '#3b281a',
    borderBottomColor: '#21150d',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  scaleInnerShadow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.42)',
    borderLeftColor: 'rgba(0,0,0,0.22)',
    borderRightColor: 'rgba(255,210,145,0.025)',
    borderBottomColor: 'rgba(255,180,90,0.06)',
  },
  scaleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  scaleBand: {
    color: '#d5b78d',
    fontFamily: 'Oswald_400Regular',
    fontSize: 11,
    letterSpacing: 1.8,
  },
  scaleTicksWrap: {
    height: 84,
    justifyContent: 'center',
  },
  ticksRow: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  tick: {
    borderRadius: 999,
  },
  tickMajor: {
    height: 42,
    width: 2,
    backgroundColor: '#e6d1b2',
    opacity: 0.9,
  },
  tickMinor: {
    height: 18,
    width: 1,
    backgroundColor: '#b89b78',
    opacity: 0.85,
  },
  slider: {
    position: 'absolute',
    left: 0,
    top: 6,
    bottom: 24,
    width: 3,
    borderRadius: 999,
    backgroundColor: '#ff9830',
    shadowColor: '#ff7a14',
    shadowOpacity: 0.9,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
    marginLeft: -1.5,
  },
  scaleBottomRow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scaleNumber: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_400Regular',
    fontSize: 11,
    letterSpacing: 0.7,
  },
  scaleGlassSheen: {
    position: 'absolute',
    left: -40,
    top: -28,
    width: CARD_W * 0.72,
    height: 90,
    opacity: 0.95,
    transform: [{ rotate: '-13deg' }],
  },
  scaleGlassMist: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,244,220,0.035)',
  },
  panel: {
    borderRadius: 18,
    padding: 8,
    marginBottom: 14,
    borderWidth: 2,
    borderTopColor: '#a98154',
    borderLeftColor: '#765737',
    borderRightColor: '#2f2015',
    borderBottomColor: '#1b120c',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.58,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  panelBevel: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,229,185,0.08)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.44)',
  },
  row: {
    flexDirection: 'row',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  blockBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,230,185,0.035)',
  },
  blockText: {
    color: '#b89b78',
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 12,
    letterSpacing: 1.7,
    textTransform: 'uppercase',
  },
  blockTextActive: {
    color: '#ffd9a0',
  },
  blockActiveUssr: {
    backgroundColor: '#3b0b08',
    borderTopColor: '#8f2a23',
    borderLeftColor: '#6d1916',
    borderRightColor: '#250604',
    borderBottomColor: '#160302',
  },
  blockActiveAxis: {
    backgroundColor: '#1f1f1f',
    borderTopColor: '#626262',
    borderLeftColor: '#474747',
    borderRightColor: '#141414',
    borderBottomColor: '#090909',
  },
  blockActiveAllies: {
    backgroundColor: '#0d2238',
    borderTopColor: '#245883',
    borderLeftColor: '#183d66',
    borderRightColor: '#071521',
    borderBottomColor: '#040b11',
  },
  controlPressed: {
    transform: [{ translateY: 2 }, { scale: 0.985 }],
    shadowOpacity: 0.1,
    opacity: 0.88,
  },
  controlDisabled: {
    shadowColor: '#ffba62',
    shadowOpacity: 0.45,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 0 },
    elevation: 7,
  },
  yearBtn: {
    width: 56,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  yearIdle: {
    backgroundColor: '#1e1712',
    borderTopColor: 'rgba(255,224,180,0.08)',
    borderLeftColor: 'rgba(255,224,180,0.05)',
    borderRightColor: 'rgba(0,0,0,0.3)',
    borderBottomColor: 'rgba(0,0,0,0.48)',
  },
  yearActive: {
    backgroundColor: '#c79852',
    borderTopColor: '#f1c77d',
    borderLeftColor: '#d9a65e',
    borderRightColor: '#7f5528',
    borderBottomColor: '#52320f',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  yearText: {
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 16,
    color: '#b89b78',
    letterSpacing: 0.8,
  },
  yearTextActive: {
    color: '#1d140e',
  },
  stationsWrap: {
    gap: 10,
    marginBottom: 18,
  },
  stationCard: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(141,107,71,0.35)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  stationCardActive: {
    borderColor: 'rgba(255, 170, 80, 0.75)',
    borderWidth: 2,
    shadowColor: '#ff7a14',
    shadowOpacity: 0.45,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 12,
  },
  stationLeft: {
    flexDirection: 'column',
    gap: 2,
  },
  stationCity: {
    color: '#f2dfc2',
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  stationBlock: {
    color: '#8e775b',
    fontFamily: 'Oswald_400Regular',
    fontSize: 10,
    letterSpacing: 1.7,
    textTransform: 'uppercase',
  },
  stationFreq: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_400Regular',
    fontSize: 14,
    letterSpacing: 0.8,
  },
  stationCityActive: {
    color: '#ffe8c4',
  },
  stationFreqActive: {
    color: '#ffc978',
  },
  emptyStationsWrap: {
    borderRadius: 18,
    paddingVertical: 22,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(141,107,71,0.25)',
    alignItems: 'center',
    marginBottom: 18,
  },
  emptyStationsText: {
    color: '#8e775b',
    fontFamily: 'Oswald_400Regular',
    fontSize: 13,
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  knobsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  knobCol: {
    alignItems: 'center',
    gap: 10,
  },
  knobOuter: {
    width: 112,
    height: 112,
    borderRadius: 999,
    borderWidth: 4,
    borderTopColor: '#a9835a',
    borderLeftColor: '#8b6b48',
    borderRightColor: '#332417',
    borderBottomColor: '#1d130c',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#16110e',
    shadowColor: '#000',
    shadowOpacity: 0.7,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  knobGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  knobRim: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    bottom: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,220,180,0.18)',
  },
  knobInnerRing: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 18,
    bottom: 18,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.15)',
  },
  knobCore: {
    position: 'absolute',
    left: 22,
    right: 22,
    top: 22,
    bottom: 22,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  knobIndicatorWrap: {
    position: 'absolute',
    top: 12,
    bottom: 12,
    left: 12,
    right: 12,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  knobIndicator: {
    width: 4,
    height: 40,
    borderRadius: 999,
    shadowColor: '#ffb45a',
    shadowOpacity: 0.75,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  knobLabel: {
    color: '#d8c3a5',
    fontFamily: 'Oswald_600SemiBold',
    fontSize: 11,
    letterSpacing: 3.1,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
});

